
title: "Neurosymbolic Systems"
url: "https://neurosymbolic-systems.github.io" # GH Pages root
baseurl: "/"                 # repo name
environment: "staging"            # env name
exclude:
  - editor-handbook.md
  - maintainer-handbook.md
